# Generated by Django 2.1.7 on 2019-04-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=128, verbose_name='路径')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('type', models.CharField(choices=[('menu', '菜单权限'), ('menuLink', '菜单链接权限'), ('button', '按钮权限')], default='button', max_length=32, verbose_name='类型')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='父级')),
            ],
            options={
                'verbose_name': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('permissions', models.ManyToManyField(to='rbac.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=32, verbose_name='密码')),
                ('roles', models.ManyToManyField(to='rbac.Role')),
            ],
            options={
                'verbose_name': '用户信息',
            },
        ),
    ]
