# Generated by Django 2.1.7 on 2019-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190421_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
            options={
                'verbose_name': '作者',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.IntegerField(choices=[(1, '已出版'), (2, '未出版')], default=1, verbose_name='出版状态'),
        ),
        migrations.AddField(
            model_name='publish',
            name='city',
            field=models.CharField(max_length=64, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='publish',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app01.Author'),
        ),
    ]
